version: '3'

volumes:
  node-modules:


services:
  app:
    build: ./
    volumes:
      - ./src/:/usr/local/src/
      - node-modules:/usr/local/src/node_modules
    working_dir: /usr/local/src
    tty: true
    container_name: chanablog
